#--------------------------------------------------------#
#--------------- MAPPING    -----------------------------#
#--------------------------------------------------------#

#--------------- ROOMS -------------------------------#
rooms:
    - name : kitchen
      pose1: [4.70,-3.23] #top_left
      pose2: [4.85,0.53]  #top_right
      pose3: [8.58,0.40] #bottom_right
      pose4: [8.57,-3.12] #bottom_left
      goal: [6.01,-1.65,0.0]
    - name : dining_room
      pose1: [4.68,-5.7] #top_left
      pose2: [4.74,-3.18]  #top_right
      pose3: [8.58,-3.32] #bottom_right
      pose4: [8.53,-5.85] #bottom_left
      goal: [5.62,-5.25,0.0]
    - name : living_room
      pose1: [4.63,-8.63] #top_left
      pose2: [4.67,-5.80]  #top_right
      pose3: [8.57,-5.80] #bottom_right
      pose4: [8.50,-8.68] #bottom_left
      goal: [6.37,-8.28,1.56]
    - name : bedroom
      pose1: [1.38,-8.64] #top_left
      pose2: [1.49,-3.84]  #top_right
      pose3: [4.72,-3.90] #bottom_right
      pose4: [4.60,-8.62] #bottom_left
      goal: [3.24,-5.11,0.0]
    - name : bathroom
      pose1: [1.44,-3.74] #top_left
      pose2: [1.55,-0.96]  #top_right
      pose3: [4.79,-1.06] #bottom_right
      pose4: [4.69,-3.80] #bottom_left
      goal: [3.43,-2.97,0.0]
    - name : entrance
      pose1: [1.47,-0.97] #top_left
      pose2: [1.52,0.62]  #top_right
      pose3: [3.44,0.55] #bottom_right
      pose4: [3.37,-0.98] #bottom_left
      goal: [2.56,-0.56,0.0]
    - name : corridor
      pose1: [3.37,-0.98] #top_left
      pose2: [3.44,0.55]  #top_right
      pose3: [4.85,0.53] #bottom_right
      pose4: [4.78,-1.04] #bottom_left
      goal: [4.2,-0.9,0.0]



#--------------- LINKS (DOORS)-----------------------#
connections: #open 0 (False), 1 (True), 2 (Unknown)
    - name: livingroom_bedroom
      rooms: ["living_room","bedroom"]
      waypoint1: [5.01,-5.37,3.14]
      waypoint2: [4.25,-5.33,3.14]
      door: true
      open: 1
    - name: bedroom_bathroom
      rooms: ["bedroom","bathroom"]
      waypoint1: [3.89,-4.33,1.56]
      waypoint2: [3.85,-3.46,1.56]
      door: true
      open: 1
    - name: bathroom_kitchen
      rooms: ["bathroom","kitchen"]
      waypoint1: [4.36,-1.76,3.14]
      waypoint2: [5.04,-1.73,3.14]
      door: true
      open: 1
    - name: entrance_corridor
      rooms: ["entrance","corridor"]
      waypoint1: [2.98,-0.27,0.0]
      waypoint2: [3.75,-0.27,0.0]
      door: true
      open: 1
    - name: fake_link
      rooms: ["dining_room","kitchen"]
      waypoint2: [5.8,-3.94,1.56]
      waypoint1: [5.8,-5.26,1.56]
    - name: side_bed_con
      rooms: ["bedroom","bedroom"]
      waypoint1: [3.9,-6.5,-2.20]
      waypoint2: [3.44,-7.2,-2.20]




objects:
    - name: bottle
      seen: true
      mapped: false
      pose: [7.13,-4.44,0.8]
      room: 'dining_room'
      furniture: 'dining_table'
      expected_rooms: ["kitchen","living_room"] # Ordered to most likely to less likely
      expected_furniture: ["kitchen_table","tv_table"]


furniture:
    - name: kitchen_table
      static: true
      mapped: true
      seen: false
      room: kitchen
      pose: [6.6,-2.1]
      orientation: 0
      size: [0.8,1.27,0.9] #measured
    - name: counter
      static: true
      mapped: true
      seen: false
      room: kitchen
      pose: [8.3,-1.4]
      orientation: 0
      size: [0.67,3.6,0.91] #measured
    - name: kitchen_sink
      static: true
      mapped: true
      seen: false
      room: kitchen
      pose: [7.37,0.16]
      orientation: 1.56
      size: [0.67,1.27,0.91] #measured

    - name: dining_table
      static: true
      mapped: true
      seen: false
      room: dining_room
      pose: [7.7,-4.5]
      orientation: 1.56
      size: [0.85,1.46,0.745] #measured

    - name: tv_table
      static: true
      mapped: true
      seen: false
      room: living_room
      pose: [8.31,-7.23]
      orientation: 0
      size: [0.415,1.35,0.395] #measured
    - name: shelf
      static: true
      mapped: true
      seen: false
      room: living_room
      pose: [8.3,-6]
      orientation: 0
      size: [0.415,0.6,1.295] #measured
    - name: sofa
      static: true
      mapped: true
      seen: false
      room: living_room
      pose: [5.1,-7.18]
      orientation: 0
      size: [0.84,1.7,0.85] #slightly measured

    - name: bed
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [2.41,-5.82]
      orientation: 1.57
      size: [1.5,2,0.53] #measured (and nailed before)
    - name: bedside_table
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [1.62,-6.8]
      orientation: 0
      size: [0.38,0.54,0.66] #measured
    - name: closet
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [4.28,-7.56]
      orientation: 0
      size: [0.56,1.115,1.9] #measured
    - name: chest
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [2.55,-8.35]
      orientation: 1.57
      size: [0.485,1.61,0.775] #measured

    - name: toilet
      static: true
      mapped: true
      seen: false
      room: bathroom
      pose: [3.11,-1.38]
      orientation: 0
      size: [0.59,0.625,0.75] #measured
    - name: sink
      static: true
      mapped: true
      seen: false
      room: bathroom
      pose: [2.27,-1.2]
      orientation: 0
      size: [0.49,0.41,0.87] #measured

#--------------------------------------------------------#
#--------------- NAVIGATION -----------------------------#
#--------------------------------------------------------#
waypoints:
      - name : tbm1_1
        pose: [5.2,-0.41,0.0] # ^
        room: kitchen
      - name: tbm1_2
        pose: [6.26,-0.61,0.0] # ^
        room: kitchen
      - name: tbm1_3
        pose: [7.42,-0.85,0.0] #turn this left >
        room: kitchen
      - name: tbm1_4
        pose: [7.42,-3.24,0.0] # turn this left (more), v
        room: kitchen
      - name: tbm1_5
        pose: [6.17,-3.36,0.0] # >
        room: dining_room
      - name: tbm1_6
        pose: [6.14,-5.45,0.0] # ^
        room: dining_room
      - name: tbm1_7
        pose: [7.58,-7.16,0.0] # >
        room: living_room
      - name: tbm1_8
        pose: [7.6,-8.32,0.0] # v
        room: living_room
      - name: tbm1_9
        pose: [6.05,-8.23,0.0] # <
        room: living_room
      - name: tbm1_10
        pose: [5.94,-6.09,0.0] # <
        room: living_room
        # After entering bedroom
        # go through bed
      - name: tbm1_11
        pose: [2.45,-7.4,0.0] #v
        room: bedroom
        # come back
      - name: tbm1_12_pre
        pose: [3.89,-4.33,0.0]
        room: bedroom
      - name: tbm1_12
        pose: [2.49,-4.5,0.0] #v
        room: bedroom
        # Go to bathroom just doors
      - name: tbm1_13
        pose: [5.76,-4.29,0.0]
        room: dining_room




paths: # type 0 door type 1 waypoint
      - name: tbm1_survey
        poses:
            - type: 0
              name: entrance_corridor
              forward: true
            - type: 1
              name: tbm1_1
            - type: 1
              name: tbm1_2
            - type: 1
              name: tbm1_3
            - type: 1
              name: tbm1_4
            - type: 1
              name: tbm1_5
            - type: 1
              name: tbm1_6
            - type: 1
              name: tbm1_7
            - type: 1
              name: tbm1_8
            - type: 1
              name: tbm1_9
            - type: 1
              name: tbm1_10
            #GO TO BEDROOM
            - type: 0
              name: livingroom_bedroom
              forward: true
            - type: 0
              name: side_bed_con
              forward: true
            - type: 1
              name: tbm1_11
            - type: 0
              name: side_bed_con
              forward: false
            - type: 1
              name: tbm1_12_pre
            - type: 1
              name: tbm1_12
              # Go to bathroom
            - type: 0
              name: bedroom_bathroom
              forward: true
              # Go to kitchen and livingroom
            - type: 0
              name: bathroom_kitchen
              forward: true
            - type: 1
              name: tbm1_13

      - name: survey2
        poses:
            - type: 0
              name: livingroom_bedroom
              forward: true
            - type: 0
              name: side_bed_con
              forward: true
            - type: 0
              name: side_bed_con
              forward: false
            - type: 0
              name: livingroom_bedroom
              forward: false





