#--------------------------------------------------------#
#--------------- MAPPING    -----------------------------#
#--------------------------------------------------------#

#--------------- ROOMS -------------------------------#
rooms:
    - name : kitchen
      pose1: [4.70,-3.23] #top_left
      pose2: [4.85,0.53]  #top_right
      pose3: [8.58,0.40] #bottom_right
      pose4: [8.57,-3.12] #bottom_left
    - name : dining_room
      pose1: [4.68,-5.7] #top_left
      pose2: [4.74,-3.18]  #top_right
      pose3: [8.58,-3.32] #bottom_right
      pose4: [8.53,-5.85] #bottom_left
    - name : living_room
      pose1: [4.63,-8.63] #top_left
      pose2: [4.67,-5.80]  #top_right
      pose3: [8.57,-5.80] #bottom_right
      pose4: [8.50,-8.68] #bottom_left
    - name : bedroom
      pose1: [1.38,-8.64] #top_left
      pose2: [1.49,-3.84]  #top_right
      pose3: [4.72,-3.90] #bottom_right
      pose4: [4.60,-8.62] #bottom_left
    - name : bathroom
      pose1: [1.44,-3.74] #top_left
      pose2: [1.55,-0.96]  #top_right
      pose3: [4.79,-1.06] #bottom_right
      pose4: [4.69,-3.80] #bottom_left
    - name : entrance
      pose1: [1.47,-0.97] #top_left
      pose2: [1.52,0.62]  #top_right
      pose3: [3.44,0.55] #bottom_right
      pose4: [3.37,-0.98] #bottom_left
    - name : corridor
      pose1: [3.37,-0.98] #top_left
      pose2: [3.44,0.55]  #top_right
      pose3: [4.85,0.53] #bottom_right
      pose4: [4.78,-1.04] #bottom_left



#--------------- LINKS (DOORS)-----------------------#
connections: #open 0 (False), 1 (True), 2 (Unknown)
    - name: door1
      rooms: ["living_room","bedroom"]
      waypoint1: [5.01,-5.37,1]
      waypoint2: [4.25,-5.33,1]
      door: true
      open: 1
    - name: door2
      rooms: ["bedroom","bathroom"]
      waypoint1: [3.89,-4.33,0.5]
      waypoint2: [3.85,-3.46,1]
      door: true
      open: 1
    - name: door3
      rooms: ["bathroom","kitchen"]
      waypoint1: [4.36,-1.76,0]
      waypoint2: [5.04,-1.73,0]
      door: true
      open: 1
    - name: door4
      rooms: ["entrance","corridor"]
      waypoint1: [2.98,-0.27,0]
      waypoint2: [3.75,-0.27,0]
      door: true
      open: 1




objects:
    - name: bottle
      seen: true
      mapped: false
      pose: [6.6,-1.7,0.85]
      room: 'kitchen'
      furniture: 'kitchen_table'
      expected_rooms: ["kitchen","living_room"] # Ordered to most likely to less likely
      expected_furniture: ["kitchen_table","tv_table"]


furniture:
    - name: kitchen_table
      static: true
      mapped: true
      seen: false
      room: kitchen
      pose: [6.6,-2.1]
      orientation: 0
      size: [0.8,1.25,0.8]
    - name: counter
      static: true
      mapped: true
      seen: false
      room: kitchen
      pose: [8.3,-1.4]
      orientation: 0
      size: [0.7,3.6,1]
    - name: kitchen_sink
      static: true
      mapped: true
      seen: false
      room: kitchen
      pose: [7.37,0.16]
      orientation: 1.56
      size: [0.7,1.4,1]

    - name: dining_table
      static: true
      mapped: true
      seen: false
      room: dining_room
      pose: [7.6,-4.52]
      orientation: 1.56
      size: [0.85,1.40,0.6]

    - name: tv_table
      static: true
      mapped: true
      seen: false
      room: living_room
      pose: [8.31,-7.23]
      orientation: 0
      size: [0.25,1.8,0.4]
    - name: shelf
      static: true
      mapped: true
      seen: false
      room: living_room
      pose: [8.3,-6]
      orientation: 0
      size: [0.3,0.6,1.4]
    - name: sofa
      static: true
      mapped: true
      seen: false
      room: living_room
      pose: [5.1,-7.18]
      orientation: 0
      size: [0.9,1.6,0.5]

    - name: bed
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [2.41,-5.82]
      orientation: 1.57
      size: [1.5,2,0.5]
    - name: bedside_table
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [1.62,-6.8]
      orientation: 0
      size: [0.38,0.53,0.6]
    - name: closet
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [4.28,-7.56]
      orientation: 0
      size: [0.6,1.1,1.8]
    - name: chest
      static: true
      mapped: true
      seen: false
      room: bedroom
      pose: [2.55,-8.35]
      orientation: 1.57
      size: [0.6,2,0.7]

    - name: toilet
      static: true
      mapped: true
      seen: false
      room: bathroom
      pose: [3.11,-1.38]
      orientation: 0
      size: [0.5,0.7,0.6]
    - name: sink
      static: true
      mapped: true
      seen: false
      room: bathroom
      pose: [2.27,-1.2]
      orientation: 0
      size: [0.4,0.3,0.8]

#--------------------------------------------------------#
#--------------- NAVIGATION -----------------------------#
#--------------------------------------------------------#
waypoints:
      - name : wayoint1
        pose: [4.17,-6.12]
        room: living_room


paths: # type 0 door type 1 waypoint
      - name: survey1
        poses:
            - type: 0
              name: door4
              forward: true
            - type: 0
              name: door3
              forward: false
            - type: 0
              name: door2
              forward: false
            - type: 0
              name: door1
              forward: false
            - type: 0
              name: door3
              forward: false



